### ISSUE TITLE
No Sensors visible in HASS

### ISSUE THREAD

**Issue by frelev** [ljmerza/ha-our-groceries#1]
Running latest HASS on Ubuntu/NUC I installed this using HACS and put the entry in the configuration.yaml. Still I have no sensors present.

In log I can see that the custom component is loaded but no errors.
what is the expected sensor name?

I have verified that username/pwd is correct and I have 3 shopping lists added in OG.

**Comment by rpitera** [comment]
Same here.  Rebooted a few times.  Verified username/password.  Also see standard custom component message indicating it was loaded:

`2019-07-23 10:58:06 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for ourgroceries which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.`

Even checked to make sure all the dependencies were met:

```
# docker container exec homeassistant pip3 install ourgroceries==1.0.3
Requirement already satisfied: ourgroceries==1.0.3 in /usr/local/lib/python3.7/site-packages (1.0.3)
Requirement already satisfied: beautifulsoup4==4.7.1 in /usr/local/lib/python3.7/site-packages (from ourgroceries==1.0.3) (4.7.1)
Requirement already satisfied: lxml==4.3.4 in /usr/local/lib/python3.7/site-packages (from ourgroceries==1.0.3) (4.3.4)
Requirement already satisfied: aiohttp==3.5.4 in /usr/local/lib/python3.7/site-packages (from ourgroceries==1.0.3) (3.5.4)
Requirement already satisfied: soupsieve>=1.2 in /usr/local/lib/python3.7/site-packages (from beautifulsoup4==4.7.1->ourgroceries==1.0.3) (1.9.2)
Requirement already satisfied: async-timeout<4.0,>=3.0 in /usr/local/lib/python3.7/site-packages (from aiohttp==3.5.4->ourgroceries==1.0.3) (3.0.1)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.7/site-packages (from aiohttp==3.5.4->ourgroceries==1.0.3) (1.3.0)
Requirement already satisfied: chardet<4.0,>=2.0 in /usr/local/lib/python3.7/site-packages (from aiohttp==3.5.4->ourgroceries==1.0.3) (3.0.4)
Requirement already satisfied: multidict<5.0,>=4.0 in /usr/local/lib/python3.7/site-packages (from aiohttp==3.5.4->ourgroceries==1.0.3) (4.5.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.7/site-packages (from aiohttp==3.5.4->ourgroceries==1.0.3) (19.1.0)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.7/site-packages (from yarl<2.0,>=1.0->aiohttp==3.5.4->ourgroceries==1.0.3) (2.8)
WARNING: You are using pip version 19.1.1, however version 19.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
#
```

Config entry:

```
ourgroceries:
  username: !secret our_groceries_username
  password: !secret our_groceries_password
```
Running 0.96.3 hass.io on VirtualBox Ubuntu VM.  Nothing in log to indicate an error with the component.

**Comment by bnhgit** [comment]
same here also.  i wrote a small python script and confirmed that the underlying library works. so at least i can run it via an automation and get a sensor populated in hass that way. note this only works with one shopping list.  use custom:todoist-list card to display sensor, or retrieve the list data from the all_tasks attribute of the sensor.ourgroceries.  not sure what's wrong with the custom component.

```
import asyncio
from ourgroceries import OurGroceries
import requests
import json

HASS_HOST = "http://<your-hass-ip>:8123"
HASS_TOKEN="a long-lived-token"
HASS_HEADERS={"content-type":"application/json", "Authorization":"Bearer {}".format(HASS_TOKEN)}
OG_USERNAME = 'your-our-groceries-username'
OG_PASSWORD = 'your-our-groceries-password'
OG_LIST_NAME = 'Shopping List'

og = OurGroceries(OG_USERNAME, OG_PASSWORD)
asyncio.run(og.login())

my_lists = asyncio.run(og.get_my_lists())
#print(my_lists)
shopping_id=''
for x in my_lists['shoppingLists']:
    if x['name'] == OG_LIST_NAME:
        shopping_id = x['id']
if shopping_id == '':
    print(OG_LIST_NAME + " not found.")
    raise SystemExit(1)

shopping_list = asyncio.run(og.get_list_items(list_id=shopping_id))
#print(shopping_list)

cnt=0
all_tasks=""
for x in shopping_list['list']['items']:
    #print(x)
    if x.get('crossedOff') is None:
         if cnt > 0:
             all_tasks = all_tasks + ","
         all_tasks = all_tasks + x['value'].replace(",",";")
         cnt=cnt+1

payload='{"state":' + str(cnt) + ', "attributes": {"custom_ui_state_card": "state-card-value_only", "all_tasks":' + json.dumps(all_tasks) + '} }'
#print(payload)
r=requests.post(HASS_HOST+"/api/states/sensor.ourgroceries",data=payload, headers=HASS_HEADERS)
print(r.text)
raise SystemExit(0)
```

**Comment by rpitera** [comment]
While this is a great workaround - thanks, btw - I'm going to wait it out a bit and hope that it gets addressed by the dev.

**Comment by ljmerza** [comment]
I'll try to add some debugger logs to see how far the code gets before it crashes (if it even loads at all). If anyone can find any kind of error that can help me out to know where to even start.

**Comment by mdezzi** [comment]
I'm having the same issue. I can see that the custom component has been added, but no sensor appears.

**Comment by ljmerza** [comment]
I made some updates and added logs everywhere in the latest version. If it still doesn't work then add debug to the logger and tell me how far you get. It will log your session cookie so make sure not to post that.

**Comment by rpitera** [comment]
I'm downloading the new version now and will get back to you with my findings.  Thanks!

**Comment by mdezzi** [comment]
Whatever you changed fixed my issue, sensor and card are now working correctly. This looks great, cant wait for added features.

**Comment by rpitera** [comment]
Same here!  I think we can close this.  And I agree it looks great so far.
