### ISSUE TITLE
0.107.6 Incompatable?

### ISSUE THREAD

**Issue by pironic** [ljmerza/ha-our-groceries#12]
HA-OUR-GROCERIES VERSION: 1.3.0
worked in ha 0.107.5 no problems... soon as i upgrade to 0.107.6:

```3/24/2020 10:52:39 AMERROR: ourgroceries 1.2.3 has requirement aiohttp==3.5.4, but you'll have aiohttp 3.6.1 which is incompatible.
3/24/2020 10:52:39 AM    ERROR: Command errored out with exit status 1:
3/24/2020 10:52:39 AM     command: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hr04q8wo/lxml/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hr04q8wo/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-t94b_9sw/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7m/lxml
3/24/2020 10:52:39 AM         cwd: /tmp/pip-install-hr04q8wo/lxml/
3/24/2020 10:52:39 AM    Complete output (88 lines):
...
...
3/24/2020 10:52:39 AM  ERROR: Failed building wheel for lxml
3/24/2020 10:52:39 AMERROR: saltbox 0.1.3 has requirement beautifulsoup4==4.8.2, but you'll have beautifulsoup4 4.7.1 which is incompatible.
3/24/2020 10:52:39 AMERROR: saltbox 0.1.3 has requirement idna==2.8, but you'll have idna 2.9 which is incompatible.
3/24/2020 10:52:39 AMERROR: saltbox 0.1.3 has requirement requests==2.22.0, but you'll have requests 2.23.0 which is incompatible.
3/24/2020 10:52:39 AMERROR: saltbox 0.1.3 has requirement soupsieve==1.9.5, but you'll have soupsieve 2.0 which is incompatible.
3/24/2020 10:52:39 AMERROR: saltbox 0.1.3 has requirement urllib3==1.25.7, but you'll have urllib3 1.25.8 which is incompatible.
3/24/2020 10:52:39 AMERROR: motorparts 1.1.0 has requirement beautifulsoup4==4.5.1, but you'll have beautifulsoup4 4.7.1 which is incompatible.
3/24/2020 10:52:39 AMERROR: gearbest-parser 1.0.7 has requirement beautifulsoup4==4.6.0, but you'll have beautifulsoup4 4.7.1 which is incompatible.
3/24/2020 10:52:39 AMERROR: ourgroceries 1.2.3 has requirement aiohttp==3.5.4, but you'll have aiohttp 3.6.1 which is incompatible.
...
...
3/24/2020 10:52:39 AMERROR: Command errored out with exit status 1: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hr04q8wo/lxml/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hr04q8wo/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-t94b_9sw/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7m/lxml Check the logs for full command output.
3/24/2020 10:52:39 AM2020-03-24 10:52:39 ERROR (MainThread) [homeassistant.setup] Setup failed for ourgroceries: Requirements for ourgroceries not found: ['ourgroceries==1.2.3'].
```

**Comment by bschatzow** [comment]
Same issue.  Broke after the update to .107.6

**Comment by rpitera** [comment]
Me too:

`Setup failed for ourgroceries: Requirements for ourgroceries not found: ['ourgroceries==1.2.3'].`

**Comment by rpitera** [comment]
May not be 0.107.x related as people were getting similar error messages back in December 2019:

https://github.com/ljmerza/ha-our-groceries/issues/7

> On startup or attempting to restart it gives the error "Component error: ourgroceries - Requirements for ourgroceries not found: ['ourgroceries==1.2.3']."

**Comment by fudu** [comment]
same error for me from 0.107.6

`Setup failed for ourgroceries: Requirements for ourgroceries not found: ['ourgroceries==1.2.3'].
24 marzo 2020, 22:31:36 – setup.py (ERROR)
Unable to install package ourgroceries==1.2.3: ERROR: Command errored out with exit status 1: command: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-25tpx2kw/lxml/setup.py'"'"'; __file__='"'"'/tmp/pip-install-25tpx2kw/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-q3wdan2f cwd: /tmp/pip-install-25tpx2kw/lxml/ Complete output (89 lines): Building lxml version 4.3.4. Building without Cython. ERROR: b'/bin/sh: xslt-config: not found\n' ** make sure the development packages of libxml2 and libxslt are installed ** Using build configuration of libxslt running bdist_wheel running build running build_py creating build creating build/lib.linux-x86_64-3.7 creating build/lib.linux-x86_64-3.7/lxml copying src/lxml/_elementpath.py -> build/lib.linux-x86_64-3.7/lxml copying src/lxml/cssselect.py -> build/lib.linux-x86_64-3.7/lxml copying src/lxml/__init__.py -> build/lib.linux-x86_64-3.7/lxml copying src/lxml/pyclasslookup.py -> build/lib.linux-x86_64-3.7/lxml copying src/lxml/ElementInclude.py -> build/lib.linux-x86_64-3.7/lxml copying src/lxml/usedoctest.py -> build/lib.linux-x86_64-3.7/lxml copying src/lxml/builder.py -> build/lib.linux-x86_64-3.7/lxml copying src/lxml/doctestcompare.py -> build/lib.linux-x86_64-3.7/lxml copying src/lxml/sax.py -> build/lib.linux-x86_64-3.7/lxml creating build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/__init__.py -> build/lib.linux-x86_64-3.7/lxml/includes creating build/lib.linux-x86_64-3.7/lxml/html copying src/lxml/html/__init__.py -> build/lib.linux-x86_64-3.7/lxml/html copying src/lxml/html/_setmixin.py -> build/lib.linux-x86_64-3.7/lxml/html copying src/lxml/html/_html5builder.py -> build/lib.linux-x86_64-3.7/lxml/html copying src/lxml/html/_diffcommand.py -> build/lib.linux-x86_64-3.7/lxml/html copying src/lxml/html/html5parser.py -> build/lib.linux-x86_64-3.7/lxml/html copying src/lxml/html/diff.py -> build/lib.linux-x86_64-3.7/lxml/html copying src/lxml/html/defs.py -> build/lib.linux-x86_64-3.7/lxml/html copying src/lxml/html/clean.py -> build/lib.linux-x86_64-3.7/lxml/html copying src/lxml/html/formfill.py -> build/lib.linux-x86_64-3.7/lxml/html copying src/lxml/html/soupparser.py -> build/lib.linux-x86_64-3.7/lxml/html copying src/lxml/html/usedoctest.py -> build/lib.linux-x86_64-3.7/lxml/html copying src/lxml/html/builder.py -> build/lib.linux-x86_64-3.7/lxml/html copying src/lxml/html/ElementSoup.py -> build/lib.linux-x86_64-3.7/lxml/html creating build/lib.linux-x86_64-3.7/lxml/isoschematron copying src/lxml/isoschematron/__init__.py -> build/lib.linux-x86_64-3.7/lxml/isoschematron copying src/lxml/etree.h -> build/lib.linux-x86_64-3.7/lxml copying src/lxml/etree_api.h -> build/lib.linux-x86_64-3.7/lxml copying src/lxml/lxml.etree.h -> build/lib.linux-x86_64-3.7/lxml copying src/lxml/lxml.etree_api.h -> build/lib.linux-x86_64-3.7/lxml copying src/lxml/includes/config.pxd -> build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/tree.pxd -> build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/xpath.pxd -> build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/xslt.pxd -> build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/relaxng.pxd -> build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/__init__.pxd -> build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/schematron.pxd -> build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/xinclude.pxd -> build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/c14n.pxd -> build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/uri.pxd -> build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/etree_defs.h -> build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/lxml-version.h -> build/lib.linux-x86_64-3.7/lxml/includes creating build/lib.linux-x86_64-3.7/lxml/isoschematron/resources creating build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/rng copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/rng creating build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/xsl copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/xsl copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/xsl creating build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1 copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1 copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1 copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1 copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1 copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1 copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1 running build_ext building 'lxml.etree' extension creating build/temp.linux-x86_64-3.7 creating build/temp.linux-x86_64-3.7/src creating build/temp.linux-x86_64-3.7/src/lxml gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -Isrc -Isrc/lxml/includes -I/usr/local/include/python3.7m -c src/lxml/etree.c -o build/temp.linux-x86_64-3.7/src/lxml/etree.o -w unable to execute 'gcc': No such file or directory Compile failed: command 'gcc' failed with exit status 1 creating tmp cc -I/usr/include/libxml2 -c /tmp/xmlXPathIniti4c1dstc.c -o tmp/xmlXPathIniti4c1dstc.o unable to execute 'cc': No such file or directory ********************************************************************************* Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed? ********************************************************************************* error: command 'gcc' failed with exit status 1 ---------------------------------------- ERROR: Failed building wheel for lxml ERROR: saltbox 0.1.3 has requirement beautifulsoup4==4.8.2, but you'll have beautifulsoup4 4.7.1 which is incompatible. ERROR: saltbox 0.1.3 has requirement idna==2.8, but you'll have idna 2.9 which is incompatible. ERROR: saltbox 0.1.3 has requirement requests==2.22.0, but you'll have requests 2.23.0 which is incompatible. ERROR: saltbox 0.1.3 has requirement soupsieve==1.9.5, but you'll have soupsieve 2.0 which is incompatible. ERROR: saltbox 0.1.3 has requirement urllib3==1.25.7, but you'll have urllib3 1.25.8 which is incompatible. ERROR: motorparts 1.1.0 has requirement beautifulsoup4==4.5.1, but you'll have beautifulsoup4 4.7.1 which is incompatible. ERROR: gearbest-parser 1.0.7 has requirement beautifulsoup4==4.6.0, but you'll have beautifulsoup4 4.7.1 which is incompatible. ERROR: ourgroceries 1.2.3 has requirement aiohttp==3.5.4, but you'll have aiohttp 3.6.1 which is incompatible. ERROR: Command errored out with exit status 1: command: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-25tpx2kw/lxml/setup.py'"'"'; __file__='"'"'/tmp/pip-install-25tpx2kw/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-764eo5m7/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7m/lxml cwd: /tmp/pip-install-25tpx2kw/lxml/ Complete output (88 lines): Building lxml version 4.3.4. Building without Cython. ERROR: b'/bin/sh: xslt-config: not found\n' ** make sure the development packages of libxml2 and libxslt are installed ** Using build configuration of libxslt running install running build running build_py creating build creating build/lib.linux-x86_64-3.7 creating build/lib.linux-x86_64-3.7/lxml copying src/lxml/_elementpath.py -> build/lib.linux-x86_64-3.7/lxml copying src/lxml/cssselect.py -> build/lib.linux-x86_64-3.7/lxml copying src/lxml/__init__.py -> build/lib.linux-x86_64-3.7/lxml copying src/lxml/pyclasslookup.py -> build/lib.linux-x86_64-3.7/lxml copying src/lxml/ElementInclude.py -> build/lib.linux-x86_64-3.7/lxml copying src/lxml/usedoctest.py -> build/lib.linux-x86_64-3.7/lxml copying src/lxml/builder.py -> build/lib.linux-x86_64-3.7/lxml copying src/lxml/doctestcompare.py -> build/lib.linux-x86_64-3.7/lxml copying src/lxml/sax.py -> build/lib.linux-x86_64-3.7/lxml creating build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/__init__.py -> build/lib.linux-x86_64-3.7/lxml/includes creating build/lib.linux-x86_64-3.7/lxml/html copying src/lxml/html/__init__.py -> build/lib.linux-x86_64-3.7/lxml/html copying src/lxml/html/_setmixin.py -> build/lib.linux-x86_64-3.7/lxml/html copying src/lxml/html/_html5builder.py -> build/lib.linux-x86_64-3.7/lxml/html copying src/lxml/html/_diffcommand.py -> build/lib.linux-x86_64-3.7/lxml/html copying src/lxml/html/html5parser.py -> build/lib.linux-x86_64-3.7/lxml/html copying src/lxml/html/diff.py -> build/lib.linux-x86_64-3.7/lxml/html copying src/lxml/html/defs.py -> build/lib.linux-x86_64-3.7/lxml/html copying src/lxml/html/clean.py -> build/lib.linux-x86_64-3.7/lxml/html copying src/lxml/html/formfill.py -> build/lib.linux-x86_64-3.7/lxml/html copying src/lxml/html/soupparser.py -> build/lib.linux-x86_64-3.7/lxml/html copying src/lxml/html/usedoctest.py -> build/lib.linux-x86_64-3.7/lxml/html copying src/lxml/html/builder.py -> build/lib.linux-x86_64-3.7/lxml/html copying src/lxml/html/ElementSoup.py -> build/lib.linux-x86_64-3.7/lxml/html creating build/lib.linux-x86_64-3.7/lxml/isoschematron copying src/lxml/isoschematron/__init__.py -> build/lib.linux-x86_64-3.7/lxml/isoschematron copying src/lxml/etree.h -> build/lib.linux-x86_64-3.7/lxml copying src/lxml/etree_api.h -> build/lib.linux-x86_64-3.7/lxml copying src/lxml/lxml.etree.h -> build/lib.linux-x86_64-3.7/lxml copying src/lxml/lxml.etree_api.h -> build/lib.linux-x86_64-3.7/lxml copying src/lxml/includes/config.pxd -> build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/tree.pxd -> build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/xpath.pxd -> build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/xslt.pxd -> build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/relaxng.pxd -> build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/__init__.pxd -> build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/schematron.pxd -> build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/xinclude.pxd -> build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/c14n.pxd -> build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/uri.pxd -> build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/etree_defs.h -> build/lib.linux-x86_64-3.7/lxml/includes copying src/lxml/includes/lxml-version.h -> build/lib.linux-x86_64-3.7/lxml/includes creating build/lib.linux-x86_64-3.7/lxml/isoschematron/resources creating build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/rng copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/rng creating build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/xsl copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/xsl copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/xsl creating build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1 copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1 copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1 copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1 copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1 copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1 copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1 running build_ext building 'lxml.etree' extension creating build/temp.linux-x86_64-3.7 creating build/temp.linux-x86_64-3.7/src creating build/temp.linux-x86_64-3.7/src/lxml gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -Isrc -Isrc/lxml/includes -I/usr/local/include/python3.7m -c src/lxml/etree.c -o build/temp.linux-x86_64-3.7/src/lxml/etree.o -w unable to execute 'gcc': No such file or directory Compile failed: command 'gcc' failed with exit status 1 cc -I/usr/include/libxml2 -c /tmp/xmlXPathInitt3duiwuz.c -o tmp/xmlXPathInitt3duiwuz.o unable to execute 'cc': No such file or directory ********************************************************************************* Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed? ********************************************************************************* error: command 'gcc' failed with exit status 1 ---------------------------------------- ERROR: Command errored out with exit status 1: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-25tpx2kw/lxml/setup.py'"'"'; __file__='"'"'/tmp/pip-install-25tpx2kw/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-764eo5m7/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7m/lxml Check the logs for full command output.
24 marzo 2020, 22:31:36 – util/package.py (ERROR)`

**Comment by BrianOfTarth** [comment]
I think what's happening here is that HA is trying to install the python dependency "ourgroceries" which is the actual Python module this component uses:

https://github.com/ljmerza/py-our-groceries

In that module, though, in the setup.py the lxml version is set as lxml==4.3.4

Now for me, using python 3.8.2, lxml version 4.3.4 cannot compile at all.  See here that there was an issue with that version https://bugs.launchpad.net/lxml/+bug/1835492 which was then fixed in version 4.3.5

So, since pip can't install the dependency for the ourgroceries python module which is a requirement for the ourgroceries component, the whole thing fails.  Note the line @pironic posted of the error:

> 3/24/2020 10:52:39 AM         cwd: /tmp/pip-install-hr04q8wo/lxml/

Also, the ourgroceries python module specifies a version of aiohttp which does not work with HA.  I think this is also a problem, though I'm not 100% sure.

That sort of confirms that's what's going on here, I think.  What needs to happen is for py-our-groceries to get a new release with an updated setup.py, and then a new ha-our-groceries release with the requirements updated to specify the new version of the ourgroceries python module.

As a workaround, I fixed this by using pip to install the ourgroceries python module while using a constraints.txt file containing the following:

```
lxml==4.4.0
aiohttp==3.6.1
```

Then I just ran `pip install -c constraints.txt ourgroceries==1.2.3` (from inside the virtualenv I run HA in) and then installed the custom_component and the lovelace card normally, and added the authentication settings in configuration.yaml.

Then, everything works fine.

**Comment by bschatzow** [comment]
Thank you for the explanation.  I'm not sure if Leonardo Merza is still supporting the card.  Is it possible that you make a branch that fixes it for the others of us that are not as fluent in coding?

**Comment by bschatzow** [comment]
Still doesn't work for me.

**Comment by ljmerza** [comment]
HA changed docker images and the new one removes some dependencies lxml needs.

**Comment by bschatzow** [comment]
See broken on .108 update.

**Comment by ljmerza** [comment]
Unless this is rewritten to not use lxml I don't think this can be fixed. Since version 106 HA used a different docker container base that doesn't contain the dependencies needed for the under lying python library to work. The only way to get this working now is to extend the HA dockerfile and add the dependencies needed to get this working again.

**Comment by burnnat** [comment]
@ljmerza What are the dependencies needed? I'm using a customized Docker container already so this would be a viable solution for me.
