### ISSUE TITLE
Version key is missing in the manifest file

### ISSUE THREAD

**Issue by alexrasmussendk** [ljmerza/ha-our-groceries#16]
### New requirement for custom components

**Version key** is required in the manifest file for future support in Home Assistant otherwise it will be blocked from running.

More information: https://developers.home-assistant.io/docs/creating_integration_manifest/#version

**Comment by rpitera** [comment]
Please update @ljmerza, should only take a few seconds and will keep this useful component working!  Thanks!

**Comment by ljmerza** [comment]
done

**Comment by rpitera** [comment]
Thanks very much!

**Comment by rpitera** [comment]
I think a version increment is required as HACS reinstall and even a remove/reinstall didn't do it.  I got around this by manually pasting the contents of the new manifest.json.  Having another problem but will put in a separate issue for it.

**Comment by ljmerza** [comment]
ok did an increment just now

**Comment by rpitera** [comment]
You may want to check #18 - another version increment may be necessary.
