### ISSUE TITLE
No 'version' key

### ISSUE THREAD

**Issue by Drewskieza** [ljmerza/ha-our-groceries#18]
## Version of the custom_component
1.3.6

Log message:
WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'ourgroceries'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'ourgroceries'

**Comment by Drewskieza** [comment]
I fixed this be reinstall 1.3.6

**Comment by ljmerza** [comment]
should work now with next version https://github.com/ljmerza/ha-our-groceries/issues/16
