### ISSUE TITLE
plans for services?

### ISSUE THREAD

**Issue by iantrich** [ljmerza/ha-our-groceries#2]
I'm pretty sure they don't have an official api, but have you looked into adding/deleting from the lists as services? I used ourgroceries back in the day but moved away because of lack of HA integration actually, so this is very cool regardless.

**Comment by ljmerza** [comment]
yeah I plan to add other functionality. I wrote the python library as well [here](https://github.com/ljmerza/py-our-groceries/) so things like deleting/adding and crossing things out need to be added ther first

**Comment by burnnat** [comment]
@ljmerza Is this something you'd be looking for contributions on? I'd also like to use add/remove services and am happy to help. But I see you already made some updates to the python library for this so I wouldn't want to duplicate effort if you have something already in the works...

**Comment by ljmerza** [comment]
All I have left is to add the lovelace card logic but I've been brainstorming how to make the UI. I'm thinking either a regular input appears or a modal for adding a new item. Also deciding on a confirm modal on delete.

**Comment by ljmerza** [comment]
@burnnat added ability to add and remove items from a list in v1.2.0
