### ISSUE TITLE
Username required, but not valid?

### ISSUE THREAD

**Issue by Spankythemusical** [ljmerza/ha-our-groceries#3]
I installed the ourgroceries component and added the section to my configuration.yaml.

Here's how it went...

config:
```
ourgroceries:
  username: !secret our_groceries_username
  password: !secret our_groceries_password
```

error:
`Invalid config for [ourgroceries]: [username] is an invalid option for [ourgroceries]. Check: ourgroceries->username. (See ?, line ?). Please check the docs at https://home-assistant.io/components/ourgroceries/`

config:
```
ourgroceries:
  #  username: !secret our_groceries_username
  #  password: !secret our_groceries_password
```

error:
```
Invalid config for [ourgroceries]: required key not provided @ data['ourgroceries']['password']. Got None
required key not provided @ data['ourgroceries']['username']. Got None. (See ?, line ?). Please check the docs at https://home-assistant.io/components/ourgroceries/
```

config:
```
ourgroceries:
  #   username: !secret our_groceries_username
  password: !secret our_groceries_password
```

error:
`Invalid config for [ourgroceries]: required key not provided @ data['ourgroceries']['username']. Got None. (See /home/homeassistant/.homeassistant/configuration.yaml, line 117). Please check the docs at https://home-assistant.io/components/ourgroceries/`

config:
```
ourgroceries:
  username: !secret our_groceries_username
  password: !secret our_groceries_password
```

error:
`Invalid config for [ourgroceries]: [username] is an invalid option for [ourgroceries]. Check: ourgroceries->username. (See ?, line ?). Please check the docs at https://home-assistant.io/components/ourgroceries/`

So a username is required, but yet a username is an invalid option?  So confusing.  My username is, as required by ourgroceries in the xxx@xxx.com format.

**Comment by ljmerza** [comment]
what version of ha?

**Comment by Spankythemusical** [comment]
Ouch, my apologies!

HA version: 0.96.0
component version: 81bf0cc

**Comment by ljmerza** [comment]
Weirdly enough, I started getting this today too when validating the config but when I restart home assistant, everything runs just fine. Removing these required fields makes the validator complain a required field is missing so I think this is a bug in home assistant itself.

**Comment by Spankythemusical** [comment]
So I just went in, un-commented everything, the did a systemctl restart rather than the HA Gui restart.  This time it was able to start up HA, but not without an interesting errors (truncated for possible security)...

`ourgroceries found _session_key <session_key identifier>`

and 
                                               
`ourgroceries found team_id <team_id identifier>`

**Comment by ljmerza** [comment]
yeah ive updated that meant to out logger.debug

**Comment by Spankythemusical** [comment]
If I restart via the HA gui, I get the “invalid option” error.  If I restart via systemctl, I still get the “session key” and “team I’d” error.

Component version: 1.1.0

**Comment by ljmerza** [comment]
is the sensor at least showing up? should be sensor.our_groceries

**Comment by Spankythemusical** [comment]
I am seeing the sensor.  I tried to put it in lovelace as a "custom:list-card" but nothing shows.

```
- columns:
              - field: shopping_lists
                title: Shopping Lists
              - field: recipies
                title: Recipies
            entity: sensor.our_groceries
            row_limit: 20
            title: Our Groceries
            type: 'custom:list-card'
```

**Comment by mdezzi** [comment]
i too am seeing this issue. After you fixed the sensor not showing up at all in the last update, i am getting the same error when i "check config". 

Sensor is working correctly though.

**Comment by cddinoj** [comment]
same issue for me also .. i am on 0.96.5. cant validate the config/ cant restart from gui. after system restart able to see the sensor

**Comment by mdezzi** [comment]
updated to 1.1.2 and this issue is still happening

**Comment by ljmerza** [comment]
Did you try restarting HA? I had the same issue until I restarted and tried validating

**Comment by mdezzi** [comment]
Yes, i restarted and was still getting the error. I just upgraded to 1.2.0 and issue seems resolved.
