### ISSUE TITLE
HA version 2022.11.2 - invalid configuration

### ISSUE THREAD

**Issue by airlabno** [ljmerza/ha-our-groceries#30]
## Configuration

```yaml

HACS 1.28.4

```

## Describe the bug
After updating HA to 2022.12.2 the addon fails to update and prevents the HA to update intirely. Is it possible to delete OurGroceries manually?

## Debug log

```text

The system cannot restart because the configuration is not valid: Package default_config setup failed. Component ourgroceries Requirements for ourgroceries not found: ['ourgroceries==1.4.1']. Integration error: ourgroceries - Requirements for ourgroceries not found: ['ourgroceries==1.4.1'].

```

**Comment by Skeletorjus** [comment]
You can comment out the ourgroceries-lines from your configuration.yaml until the issue is fixed.

Like this:
```
#ourgroceries:
#  username: !secret our_groceries_username
#  password: !secret our_groceries_password
```

**Comment by maustru** [comment]
i have the same problem with the newest version, but i want to use it. is there a possibility?

`2023-01-06 21:45:55.852 ERROR (MainThread) [homeassistant.bootstrap] Failed to parse configuration.yaml: Secret MyMailAdress@gmail.com not defined. Activating safe mode`

**Comment by ljmerza** [comment]
your secret is not defined in the secrets file
