### ISSUE TITLE
Can't seem to install

### ISSUE THREAD

**Issue by malaki86** [ljmerza/ha-our-groceries#32]
I can't seem to get the integration to install correctly and looking for advice.

Steps taken:
  Installed v1.5.1 (today's fix) via HACS
  Added the 'ourgroceries' section to the config/configuration.yaml file
  Restarted

The ourgroceries device/integration does not appear in the devices or entities screens. I also installed the Lovelace card addon, but I can't find it in the "cards" list. 

I put my username and password directly into the configuration.yaml file (username: my@email.com). Do I need to put that in quotes? Single or double?

**Comment by malaki86** [comment]
Ok, I managed to get the integration to load. Username and password in single quotes.

 I  still can't get the card to appear.

**Comment by malaki86** [comment]
Added single quotes around username and password directly in the configuration.yaml file

**Comment by kovrom** [comment]
> I can't seem to get the integration to install correctly and looking for advice.
> 
> Steps taken: Installed v1.5.1 (today's fix) via HACS Added the 'ourgroceries' section to the config/configuration.yaml file Restarted
> 
> The ourgroceries device/integration does not appear in the devices or entities screens. I also installed the Lovelace card addon, but I can't find it in the "cards" list.
> 
> I put my username and password directly into the configuration.yaml file (username: [my@email.com](mailto:my@email.com)). Do I need to put that in quotes? Single or double?

Very often you won't see custom cards names in the list. In that case choose "Manual" and add the code from the card example. For Our Groceries that would be something like:
```
type: custom:our-groceries-card
title: Our Groceries 
show_header: true
entity: sensor.our_groceries
show_crossed_off: false
```
