### ISSUE TITLE
Error during setup of component ourgroceries

### ISSUE THREAD

**Issue by neilmartin83** [ljmerza/ha-our-groceries#35]
## Version of the custom_component

1.5.1

## Configuration

```yaml

# OurGroceries
ourgroceries:
  username: !secret ourgroceries_username
  password: !secret ourgroceries_password

```

## Describe the bug
Home Assistant is failing to set up the ourgroceries integration following a restart today at 3:00 GMT. No known changes to the instance or our lists occurred between now and the last time I restarted my HA instance (which was yesterday around 21:00).

## Debug log

```text

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 253, in _async_setup_component
    result = await task
  File "/config/custom_components/ourgroceries/__init__.py", line 66, in async_setup
    await og.login()
  File "/usr/local/lib/python3.10/site-packages/ourgroceries/__init__.py", line 109, in login
    await self._get_master_list_id()
  File "/usr/local/lib/python3.10/site-packages/ourgroceries/__init__.py", line 151, in _get_master_list_id
    self._master_list_id = re.findall(REGEX_MASTER_LIST_ID, responseText)[0]
IndexError: list index out of range

```

Full debug logs attached - the error occurred at around 08:41:36 - looks like ourgroceries loaded at 08:41:29.477
[home-assistant_2023-01-18T08-41-49.334Z.log.zip](https://github.com/ljmerza/ha-our-groceries/files/10443918/home-assistant_2023-01-18T08-41-49.334Z.log.zip)

**Comment by neilmartin83** [comment]
Just to add - based on my limited knowledge of using REST APIs, this looks like it could be down to a possible API change from Our Groceries itself - i.e. if the response is not what we usually when trying to get the master list ID from them.

And thank you for this component, it's made my life so much easier when it comes to shopping and meal planning - automating HA to add items from our meal plan recipes to the list each week is game changing!

**Comment by neilmartin83** [comment]
Digging in - I think I've found it.

There's a change on https://www.ourgroceries.com/your-lists - I believe the regex in https://github.com/ljmerza/py-our-groceries/blob/master/ourgroceries/__init__.py#L47 needs to change to:

```
r'href="/your-lists/list/(.*)">Manage master list'
```

I've tested this on regex101.com and it matches the pattern and group, grabbing my master list ID.

**Comment by kovrom** [comment]
Exactly same issue here.

**Comment by waynetd777** [comment]
Same issue here

**Comment by CodyJon** [comment]
Also having exact same issues

**Comment by neilmartin83** [comment]
Just wanted to confirm - the regex change I've proposed in https://github.com/ljmerza/py-our-groceries/pull/19 fixes this issue.

Fingers crossed it's merged and an update is released.

**Comment by kovrom** [comment]
> 

Thank you for finding the problem!  Yeah, let's hope @ljmerza will have time soon to merge the fix. Always a pain when service decides to change api, calls structure, etc.

**Comment by CodyJon** [comment]
Is forking this and changing `r'href="/your-lists/list/(.*)">Manage master list'` ?

As I cannot seem to see it in the init_.py file on studio code. Many thanks for this addon as I use it quite frequently and hope the fix gets merged in soon.

**Comment by neilmartin83** [comment]
Heya @CodyJon the file in question is part of the ourgroceries Python module, which this HA integration depends on, and not the __init__.py file included with the integration itself. I raised the issue here because it manifested in my HA instance, before I realised where it was actually coming from.

The file in question is here: `/usr/local/lib/python3.10/site-packages/ourgroceries/__init__.py` (but you can't get to it easily in HA).

**Comment by ljmerza** [comment]
v1.5.2 fixes this. thanks @neilmartin83 for looking into this

**Comment by kovrom** [comment]
> v1.5.2 fixes this. thanks @neilmartin83 for looking into this

Works perfectly. Thank you for the quick fix!
