### ISSUE TITLE
HA 11.0 added a todo list

### ISSUE THREAD

**Issue by bschatzow** [ljmerza/ha-our-groceries#41]
**Is your feature request related to a problem? Please describe.**
Is there anyway to add our Groceries integration to the new ToDO dashboard?

**Describe the solution you'd like**
Would be nice to be able to see the shopping list in the side bar.

**Describe alternatives you've considered**

**Additional context**

**Comment by Skeletorjus** [comment]
Home Assistant 2023.12.0b0 adds a OurGroceries integration with support for the to-do list.
https://rc.home-assistant.io/integrations/ourgroceries

**Comment by bschatzow** [comment]
Resolved with new integration

**Comment by bschatzow** [comment]
Resolved
