### ISSUE TITLE
1.1.2 release identical to 1.1.1?

### ISSUE THREAD

**Issue by burnnat** [ljmerza/ha-our-groceries#5]
Looking at the Releases tab, it looks like the tags for [1.1.2](https://github.com/ljmerza/ha-our-groceries/releases/tag/1.1.2) and [1.1.1](https://github.com/ljmerza/ha-our-groceries/releases/tag/1.1.1) are both pointing to the same commit, d08da0d. I would expect maybe 1.1.2 was intended to point to 2c52dd1 instead?

**Comment by ljmerza** [comment]
might have but i just released version 1.2.0 so this should be fixed. thanks for the heads up
