### ISSUE TITLE
Add/remove items, create lists etc?

### ISSUE THREAD

**Issue by papst01** [ljmerza/ha-our-groceries#8]
Maybe I missed it, but how can I add/cross out/remove items to/from a shopping list or create/remove shopping lists via home assistant service?

**Comment by burnnat** [comment]
Hi @papst01, right now I believe there is only a REST API for making modification to lists. I just opened a pull request #9 that adds service calls for adding, removing, and copying items between lists. It doesn't include creating or deleting whole lists but that would be straightforward to add once the initial PR is approved.

**Comment by ljmerza** [comment]
Thanks for looking into this. I haven't been able to touch my HA based repos in a few months due to new work related projects taking priority but still plan to one day catch up.

**Comment by ljmerza** [comment]
added in v1.3.0 let me know if they work out for you and we can close this

**Comment by papst01** [comment]
yeah tested it (add and remove items). And it works fine. Thank you very much.

Little bit off topic but I wanted to add one thing here: If you want to build an ifttt-connection with home assistant to call ourgroceries.add_to_list, don't use the **items**  in the POST section like seen here
`{ "action":"call_service_og", "service":"ourgroceries.add_to_list", "list_id":"My List", "items": " {{TextField}}" }`
because **items** is a reserverd word. If you do use **items** in your automation or IFTTT post section you will get items added to your liste like
`<built-in method items of dict object at 0x7ffxxxxx>`
Because of that I use **things** instead of.  On the home assistant side the automation side would look like this:
```
data_template:
  items: '{{ trigger.event.data.things}}'
  list_id: '{{ trigger.event.data.list_id }}'
service_template: '{{ trigger.event.data.service }}'
```
